services: 
  glance:
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped
    ports:
      - "2002:8080"
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy
    environment:
      - WEBSERVER_API_PASSWORD=${WEBSERVER_API_PASSWORD}
      - AGENT_TOKEN=${AGENT_TOKEN}

networks:
  proxy:
    external: true
