- name: install prerequisites
  ansible.builtin.apt:
    pkg:
      - ca-certificates
      - curl
    state: present

- name: add repository
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: https://download.docker.com/linux/debian
    suites: '{{ ansible_distribution_release }}'
    components: stable
    architectures: amd64
    signed_by: https://download.docker.com/linux/debian/gpg
    state: present

- name: install
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true

- name: start
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: setup network
  community.docker.docker_network:
    name: '{{ network }}'

- name: add user to group
  user:
    name: administrator
    groups: docker
    append: true
