- name: start container
  community.docker.docker_container:
    name: caddy
    image: ghcr.io/caddybuilds/caddy-cloudflare:latest
    restart: true
    ports:
      - '2000:80'
      - '443:443'
      - '443:443/udp'
    volumes:
      - /home/administrator/services/docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - name: '{{ docker_network }}'
    env:
      CLOUDFLARE_API_TOKEN: '{{ cloudflare_api_token }}'
    state: recreate
